### ISSUE TITLE
Login loop - no errors or exceptions.

### ISSUE THREAD

**Issue by clarkd** [umbraco/UmbracoIdentityExtensions#20] opened 2017-06-23 08:35 UTC
Hi. 

I'm having an issue with a new Umbraco 7.6 site. We've setup external auth with Azure Active Directory. That all appears to be working fine, but after a random period of time (seemingly) it stops working and our users cannot login. Clicking the "Login with Azure" does the redirection to Microsoft, but on return they just end up on back on the login page. I have to manually restart the app to get it working again. Sometimes it'll work for a few days, sometimes a few hours.

There doesn't appear to be any exceptions logged so I'm not sure where to start debugging. Any ideas?

**Comment by aclave1** [comment] 2017-08-04 20:10
@clarkd Have you solved this yet?

**Comment by clarkd** [comment] 2017-08-04 20:11
No - although I'm not too sure where to start debugging the issue! Are you
experiencing the same issue?

**Comment by aclave1** [comment] 2017-08-05 22:41
Yes I was experiencing the same issue but I was able to figure it out using the code from [this article](https://www.jdibble.co.uk/blog/securing-umbraco-backoffice-with-azure-active-directory/). If you posted some of your code maybe I take a stab at it.

**Comment by clarkd** [comment] 2017-08-17 12:51
@aclave1 This is the code I have in UmbracoADAzureExtensions.cs... Would certainly appreciate you taking a look or sharing your version. I used the article you indicated but also hit a few problems along the way so the code does vary slightly... 

```
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.IdentityModel.Protocols;
using Microsoft.Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Notifications;
using Owin;
using Umbraco.Core;
using Umbraco.Web.Security.Identity;
using Microsoft.Owin.Security.OpenIdConnect;
using Umbraco.Core.Models.Identity;
using Umbraco.Core.Security;
using Constants = Umbraco.Core.Constants;

namespace ASP
{
    public static class UmbracoADAuthExtensions
    {

        ///  <summary>
        ///  Configure ActiveDirectory sign-in
        ///  </summary>
        ///  <param name="app"></param>
        ///  <param name="tenant"></param>
        ///  <param name="clientId"></param>
        ///  <param name="postLoginRedirectUri">
        ///  The URL that will be redirected to after login is successful, example: http://mydomain.com/umbraco/;
        ///  </param>
        ///  <param name="issuerId">
        /// 
        ///  This is the "Issuer Id" for you Azure AD application. This a GUID value and can be found
        ///  in the Azure portal when viewing your configured application and clicking on 'View endpoints'
        ///  which will list all of the API endpoints. Each endpoint will contain a GUID value, this is
        ///  the Issuer Id which must be used for this value.        
        /// 
        ///  If this value is not set correctly then accounts won't be able to be detected 
        ///  for un-linking in the back office. 
        /// 
        ///  </param>
        /// <param name="caption"></param>
        /// <param name="style"></param>
        /// <param name="icon"></param>
        /// <remarks>
        ///  ActiveDirectory account documentation for ASP.Net Identity can be found:
        ///  https://github.com/AzureADSamples/WebApp-WebAPI-OpenIDConnect-DotNet
        ///  </remarks>
        public static void ConfigureBackOfficeAzureActiveDirectoryAuth(this IAppBuilder app, 
            string tenant, string clientId, string postLoginRedirectUri, Guid issuerId,
            string caption = "Active Directory", string style = "btn-microsoft", string icon = "fa-windows")
        {
            //var authority = string.Format(
            //    CultureInfo.InvariantCulture, 
            //    "https://login.windows.net/{0}", 
            //    tenant);

            var authority = string.Format(
                CultureInfo.InvariantCulture,
                "https://login.microsoftonline.com/{0}",
                tenant);

            var adOptions = new OpenIdConnectAuthenticationOptions
            {
                SignInAsAuthenticationType = Constants.Security.BackOfficeExternalAuthenticationType,
                ClientId = clientId,
                Authority = authority,
                RedirectUri = postLoginRedirectUri,
                AuthenticationMode = AuthenticationMode.Passive,
                Notifications = new OpenIdConnectAuthenticationNotifications()
                {
                    AuthorizationCodeReceived = AuthorizationCodeReceived,
                    SecurityTokenValidated = SecurityTokenValidated
                }
            };

            adOptions.ForUmbracoBackOffice(style, icon);            
            adOptions.Caption = caption;
            //Need to set the auth tyep as the issuer path
            adOptions.AuthenticationType = string.Format(
                CultureInfo.InvariantCulture,
                "https://sts.windows.net/{0}/",
                issuerId);

            adOptions.SetExternalSignInAutoLinkOptions(new ExternalSignInAutoLinkOptions(autoLinkExternalAccount: true));

            app.UseOpenIdConnectAuthentication(adOptions);            
        }

        private static async Task AuthorizationCodeReceived(AuthorizationCodeReceivedNotification context)
        {
            var userService = ApplicationContext.Current.Services.UserService;

            var email = context.JwtSecurityToken.Claims.First(x => x.Type == "upn").Value;
            var issuer = context.JwtSecurityToken.Claims.First(x => x.Type == "iss").Value;
            var providerKey = context.JwtSecurityToken.Claims.First(x => x.Type == "sub").Value;
            var name = context.JwtSecurityToken.Claims.First(x => x.Type == "name").Value;
            var userManager = context.OwinContext.GetUserManager<BackOfficeUserManager>();

            var user = userService.GetByEmail(email);

            if (user == null)
            {
                var writerUserType = userService.GetUserTypeByName("writer");
                user = userService.CreateUserWithIdentity(email, email, writerUserType);
            }

            var identity = await userManager.FindByEmailAsync(email);
            if (identity.Logins.All(x => x.ProviderKey != providerKey))
            {
                identity.Logins.Add(new IdentityUserLogin(issuer, providerKey, user.Id));
                identity.Name = name;
                var result = userManager.Update(identity);
            }
        }

        private static async Task SecurityTokenValidated(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> n)
        {
            var identityUser = n.AuthenticationTicket.Identity;

            var newIdentityUser = new ClaimsIdentity(identityUser.AuthenticationType, ClaimTypes.GivenName, ClaimTypes.Role);

            newIdentityUser.AddClaim(new Claim(ClaimTypes.Email, identityUser.Name));
            newIdentityUser.AddClaim(new Claim(ClaimTypes.Upn, identityUser.Name));
            newIdentityUser.AddClaim(identityUser.FindFirst(ClaimTypes.NameIdentifier));
            newIdentityUser.AddClaim(identityUser.FindFirst(ClaimTypes.GivenName));

            n.AuthenticationTicket = new AuthenticationTicket(newIdentityUser, n.AuthenticationTicket.Properties);
        }
    }
    
}
```

**Comment by arlan85** [comment] 2018-01-24 18:13
@aclave1 and @clarkd I have the same issue on Umbraco 7.6.3. The code I use is the same in the post, but for some reason I keep having the same behavior, randomly the login sends me after I login with AAD to the Umbraco login page and in the Chrome console tells me: postlogin = false. Did you get any feedback about this?

**Comment by aclave1** [comment] 2018-01-24 23:36
@arlan85 One of my main issues was that some of my settings were wrong. Make sure your reply url in azure matches the one you provide in umbraco and make sure the schemes match.

**Comment by arlan85** [comment] 2018-01-25 13:43
@aclave1 the login process works fine, but always when redirects after login, it comes to the umbraco login again over and over.

**Comment by mark-data8** [comment] 2018-02-28 11:15
I'm having the same issue - after logging in with AAD I get redirected back to the login page. All the code in `AuthorizationCodeReceived` executes as expected, and I don't see any exceptions thrown. Any ideas where I can start looking?

**Comment by danwhite85** [comment] 2018-05-21 23:35
Anyone solve this yet?

**Comment by Enoch-Ye** [comment] 2018-05-21 23:51
We are also facing the same issue on 7.8.1 that user gets redirected back to login page without any exception. Appreciate any help.

**Comment by Shazwazza** [comment] 2018-05-30 05:55
Sounds like the required claims are missing. Not sure what everyone's code is doing but the above snippet is doing some claim transformations in `SecurityTokenValidated` for whatever reason. The original article mentioned above (https://www.jdibble.co.uk/blog/securing-umbraco-backoffice-with-azure-active-directory/) doesn't do this. I'd suggest keeping everything as simple as possible before modifying the whole login flow and if you've copy/pasted some code please make sure you know what it's doing.

The code to create an umbraco back office identity from a claims identity is here: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Security/UmbracoBackOfficeIdentity.cs#L26 ... which means you will need all required claims (which vary based on the umbraco version).  

The original article doesn't do any claims transformations so that approach should still work ... but be sure you aren't using any Obsolete methods.

**Comment by Shazwazza** [comment] 2018-05-30 05:57
Though since there's no errors, it may be something else. I had a similar problem when trying to debug Azure easy auth ... make sure this is NOT on! see here for full details https://shazwazza.com/post/getting-umbraco-to-work-with-azure-easy-auth/  If you are using easy auth then you shouldn't really be mixing the two technologies, but i suppose you can if you follow that guide.

If that's not the issue than if you have exact steps to replicate this from a vanilla Umbraco install please post those steps and i'll see what i can find.

**Comment by Fjellvang** [comment] 2018-05-30 10:50
We have the same issue using AD FS instead of Azure for authorisation. It fails after a while in production, and requires a reset of the app pool to work again ..

**Comment by arlan85** [comment] 2018-06-01 13:00
All my apps have App Service Authentication OFF (Anonymous access is enabled on the App Service app. Users will not be prompted for login.). This issue is weird and randomly, even if you restart the app, the Azure Authentication redirects you to the login page, but in some cases making a swap between slots in the same app, it works. So, is a  frequent, randomly but annoying issue.

**Comment by Fjellvang** [comment] 2018-06-04 09:19
in our failing ADFS Solution we noticed that the redirect cookie is missing a lot of information from umbraco. Specifically UMB_EXTLOGIN and UMB_UCONTEXT, the user get authenticated through ADFS, but it makes sense that it loops if there is no Umbraco information the in cookie i guess.

**Comment by aclave1** [comment] 2018-06-07 21:28
The issue occurs for me after a few days. I have deployed a potential fix to one of my client sites today. I will update you all with the fix if it works!

**Comment by christ76** [comment] 2018-09-17 17:06
We have the same issue here with Umbraco version 7.11.1 assembly: 1.0.6750.39767.  Anyone manage to fix this? Thanks!

**Comment by nul800sebastiaan** [comment] 2018-11-15 10:36
Tough one! While I recognize that a few people are battling this issue, we've not had any way to reproduce the issue yet. In cases like this I would start adding copious logging to our source code and deploy custom builds to at least get an idea of what might be going on and where.

I will close this issue for now until we can get some way to reproduce the problem. Fingers crossed 🤞 that we can get to the bottom of this one day!

**Closed by nul800sebastiaan** 2018-11-15 10:36 UTC
Labels: category/question

**Comment by clarkd** [comment] 2018-11-15 10:58
Seems absurd to close this issue...

**Comment by arlan85** [comment] 2018-11-15 13:41
@clarkd I'm agree with you, we gave all information we have because it is a random issue, today I had again to redeploy my website because my editors can't login into the site. Is is so odd but it happens!


> Tough one! While I recognize that a few people are battling this issue, we've not had any way to reproduce the issue yet. In cases like this I would start adding copious logging to our source code and deploy custom builds to at least get an idea of what might be going on and where.
> 
> I will close this issue for now until we can get some way to reproduce the problem. Fingers crossed 🤞 that we can get to the bottom of this one day!

**Comment by clarkd** [comment] 2018-11-16 11:18
@Shazwazza  The only pointer I might be able to add is that I think it might be related to some kind of inactivity - we used to experience this problem reasonably regularly but we've since grown in number of employees so our site (internal portal) is being accessed more regularly and I haven't seen the issue in a while - try leaving the site for a few days or something. FYI, we were using Azure AD auth.

**Comment by CasperTDK** [comment] 2018-11-19 15:20
Just to chime in. We have the exact same code and issue. A recycle of app pool works. We have hundreds of editors on the site with the issue, and right now they are resorting to use a single umbraco username+password login, while this issue gets resolved

**Comment by Shazwazza** [comment] 2018-11-20 00:40
Hi all, please try to not report bugs by saying

> We have the exact same code and issue

Because I don't actually know what the 'exact code' you are actually using is. What is the actual code you are referring too? There's only one code block listed above https://github.com/umbraco/UmbracoIdentityExtensions/issues/20#issuecomment-323064200 and I've mentioned that to get to the bottom of this, we need to remove all complexity in the code https://github.com/umbraco/UmbracoIdentityExtensions/issues/20#issuecomment-393039094

So, for people having this problem what code are you actually using and why? please be specific. I've implemented this on my own site but i'm using the basic code provided with Identity Extensions, not with a lot of claims transformations and custom logic as posted above.

**Comment by Shazwazza** [comment] 2018-11-20 00:43
I wrote a post yesterday on implementing Azure AD Auth https://shazwazza.com/post/configuring-azure-active-directory-login-with-umbraco/ so if you are doing things in code in vastly different ways i need to know why and if that is part of the problem (i.e. if you just implement it the simplest way, is it still a problem?)

**Comment by CasperTDK** [comment] 2018-11-20 08:14
Alright I will share some more code and I'd test anything you would ask me to.

`using System;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Security.Claims;
using System.Threading.Tasks;
using FrontendTemplate.MVC;
using log4net;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.IdentityModel.Protocols;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Notifications;
using Microsoft.Owin.Security.OpenIdConnect;
using Owin;
using Umbraco.Core;
using Umbraco.Core.Models.Identity;
using Umbraco.Core.Models.Membership;
using Umbraco.Core.Security;
using Umbraco.Web.Security.Identity;

namespace KLDK.Web
{
    public class KLAuth
    {
        protected static readonly ILog Log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);

        public static void ConfigureBackOfficeAzureActiveDirectoryAuth(IAppBuilder app)
        {
            string clientId = ConfigurationManager.AppSettings["ida:ClientId"];
            string tenantId = ConfigurationManager.AppSettings["ida:TenantId"];
            string caption = ConfigurationManager.AppSettings["ida:Caption"];
            var uri = string.IsNullOrEmpty(ConfigurationManager.AppSettings["customDomainName"]) ? ConfigurationManager.AppSettings["bindingurl"] : ConfigurationManager.AppSettings["customDomainName"];
            var loginRedirectUri = new UriBuilder(uri)
            {
                Port = -1,
                Path = "umbraco",
                Scheme = GeneralConfiguration.AppSettingValueOrDefault("MW.Umbraco.forceHttps", false) ? Uri.UriSchemeHttps : Uri.UriSchemeHttp
            };
            var postLoginRedirectUri = loginRedirectUri;
            var issuerId = new Guid(tenantId);

            string style = "btn-microsoft";
            string icon = "fa-windows";

            var authority = string.Format(
                CultureInfo.InvariantCulture,
                "https://login.microsoftonline.com/{0}",
                tenantId);


            var adOptions = new OpenIdConnectAuthenticationOptions
            {
                SignInAsAuthenticationType = Constants.Security.BackOfficeExternalAuthenticationType,
                ClientId = clientId,
                Authority = authority,
                RedirectUri = postLoginRedirectUri.ToString(),
                AuthenticationMode = AuthenticationMode.Passive,
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = SecurityTokenValidated,
                    AuthorizationCodeReceived = AuthorizationCodeReceived,
                    MessageReceived = (notification) =>
                    {
                        Log.Debug($"MessageReceived: ({notification.ProtocolMessage.PostTitle} {notification.State})");
                        return Task.FromResult(0);
                    },
                    AuthenticationFailed = (context) =>
                    {
                        Log.Error($"AuthenticationFailed: {context.Exception.Message} ({context.ProtocolMessage})");
                        if (context.Exception.Message.StartsWith("OICE_20004") || context.Exception.Message.Contains("IDX10311"))
                        {
                            context.SkipToNextMiddleware();
                            return Task.FromResult(0);
                        }
                        return Task.FromResult(0);
                    },
                    SecurityTokenReceived = (notification) =>
                    {
                        Log.Debug($"SecurityTokenReceived: ({notification.ProtocolMessage.PostTitle} {notification.State})");
                        return Task.FromResult(0);
                    },
                    RedirectToIdentityProvider = (notification) =>
                    {
                        Log.Debug($"RedirectToIdentityProvider: ({notification.ProtocolMessage.PostTitle} {notification.State})");
                        return Task.FromResult(0);
                    },
                },
                AuthenticationType = Umbraco.Core.Constants.Security.BackOfficeTokenAuthenticationType,
            };

            adOptions.ForUmbracoBackOffice(style, icon);
            adOptions.Caption = caption;
            //Need to set the auth tyep as the issuer path
            adOptions.AuthenticationType = string.Format(
                CultureInfo.InvariantCulture,
                "https://sts.windows.net/{0}/",
                issuerId);

            adOptions.SetExternalSignInAutoLinkOptions(new ExternalSignInAutoLinkOptions(true, defaultUserGroups: null, defaultCulture: ConfigurationManager.AppSettings["umbracoDefaultUILanguage"]));

            app.UseOpenIdConnectAuthentication(adOptions);
        }

        private static async Task AuthorizationCodeReceived(AuthorizationCodeReceivedNotification context)
        {
            var userService = ApplicationContext.Current.Services.UserService;

            var emailClaim = context.JwtSecurityToken.Claims.FirstOrDefault(x => x.Type == "email") ?? context.JwtSecurityToken.Claims.FirstOrDefault(x => x.Type == "upn");
            var email = emailClaim.Value.Replace("mediaworkers.dk", "kruso.dk");
            var issuer = context.JwtSecurityToken.Claims.First(x => x.Type == "iss").Value;
            var providerKey = context.JwtSecurityToken.Claims.First(x => x.Type == "sub").Value;
            var name = context.JwtSecurityToken.Claims.First(x => x.Type == "name").Value;
            var userManager = context.OwinContext.GetUserManager<BackOfficeUserManager>();

            var user = userService.GetByEmail(email);
            Log.Info($"Trying to authenticate user: {email}");

            if (user == null)
            {
                //todo
                IReadOnlyUserGroup userGroupByAlias;
                Log.Info($"User not found in umbraco. Creating user...");

                if (email.EndsWith("kruso.dk"))
                {
                    userGroupByAlias = userService.GetUserGroupByAlias("admin") as IReadOnlyUserGroup;
                }
                else
                {
                    userGroupByAlias = userService.GetUserGroupByAlias("employee") as IReadOnlyUserGroup;
                }
                user = userService.CreateUserWithIdentity(email, email);
                user.AddGroup(userGroupByAlias);
                userService.Save(user);
            }
            else
            {
                Log.Debug($"User exists in umbraco");
            }

            var identity = await userManager.FindByEmailAsync(email);
            if (identity.Logins.All(x => x.ProviderKey != providerKey))
            {
                identity.Logins.Add(new IdentityUserLogin(issuer, providerKey, user.Id));
                identity.Name = name;
                Log.Info($"Adding identification to user");
                await userManager.UpdateAsync(identity);
            }
        }

        private static async Task<int> SecurityTokenValidated(SecurityTokenValidatedNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> n)
        {
            Log.Debug($"SecurityTokenValidated: ({n.ProtocolMessage.PostTitle} {n.State})");
            var identityUser = n.AuthenticationTicket.Identity;

            var newIdentityUser = new ClaimsIdentity(identityUser.AuthenticationType, ClaimTypes.GivenName, ClaimTypes.Role);

            newIdentityUser.AddClaim(new Claim(ClaimTypes.Email, identityUser.Name));
            newIdentityUser.AddClaim(new Claim(ClaimTypes.Upn, identityUser.Name));

            var nameIdentifier = identityUser.FindFirst(ClaimTypes.NameIdentifier);
            var givenName = identityUser.FindFirst(ClaimTypes.GivenName);

            if (nameIdentifier != null)
            {
                newIdentityUser.AddClaim(nameIdentifier);
            }
            if (givenName != null)
            {
                newIdentityUser.AddClaim(givenName);
            }

            n.AuthenticationTicket = new AuthenticationTicket(newIdentityUser, n.AuthenticationTicket.Properties);

            Log.Info($@"ADFS USER login. Name: {givenName?.Value ?? "NULL"} Email: {identityUser.Name}");

            return await Task.FromResult(0);
        }
    }
}`

I've tried disabling the `SecurityTokenValidated` event.
I only see success statements in the log.

The strangest part is that the login **works** but periodically. An app-pool recycle seems to help, but again, only for a period.
The reason for the 'complexity' is that the Azure AD provider does not provide email in the expected claim and we need to do some transformations.

**Comment by Shazwazza** [comment] 2018-11-20 09:02
Can you try updating these dependencies to these versions:

https://www.nuget.org/packages/Microsoft.Owin.Security/3.1.0
https://www.nuget.org/packages/Microsoft.Owin.Security.OpenIdConnect/3.1.0
https://www.nuget.org/packages/Microsoft.IdentityModel.Protocol.Extensions/1.0.4.403061554
https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/4.0.4.403061554

Is there anything else i might need to know like is load balancing involved?

**Comment by CasperTDK** [comment] 2018-11-20 09:09
Okay. Will do that now. 

Hmm no, it is pretty straight forward setup. 1 server (Windows Server 2016 standard) and 1 instance of umbraco.
The customer wants to only be authenticated through their Azure AD.

**Comment by Shazwazza** [comment] 2018-11-20 09:15
ok thanks, at least we can rule out LB. It does seems odd that restarting the appdomain would fix it, i don't think there's a hidden cache within this setup. Let me know if you have any success with the updated libs. There's a 5.x (aspnet core compat) version of the Jwt one but i'm unsure if it's compatible, i'd need to test so not sure at this point.

**Comment by clarkd** [comment] 2018-11-20 10:44
@Shazwazza We're on Umbraco Cloud FYI so nothing atypical about our setup. Same workaround for us was to recycle the app pool (in our case, by toggling Debug mode on/off through Cloud UI). We're happy to add some additional tracing/logging if you point us in the right direction :)

**Comment by Shazwazza** [comment] 2018-11-29 00:05
Some of the code snippets above show that some logging is taking place at every possible corner of the OAuth process as far as OWIN goes, if none of those logs are yielding anything then I can only imagine that its something taking place within the BackOfficeController https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Editors/BackOfficeController.cs#L319 

Perhaps this doesn't succeed but is returning no errors so you don't see anything? https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Editors/BackOfficeController.cs#L332

**Comment by CasperTDK** [comment] 2018-11-29 11:31
@Shazwazza I can't find a way to expose/log value of TempData[TokenExternalSignInError] = result.Errors; 
any ideas?

**Comment by Shazwazza** [comment] 2018-11-29 23:19
You would see if there are errors in there in the UI when you login, that's what i'm saying above, perhaps that call is failing without returning any errors, only thing you can do is create a custom build of Umbraco and add logging throughout that method and/or step through the code to see what might be happening.

Another question: Do you guys have session timeouts enabled? i.e. `umbracoTimeOutInMinutes` in web.config and `<keepUserLoggedIn>false</keepUserLoggedIn>` in umbracoSettings.config ?

**Comment by Shazwazza** [comment] 2018-11-29 23:23
On a side note - unfortunately i haven't been able to see this problem at all in my own implementation for Azure AD + Umbraco. It's been running for over a week and I log in each day without issue 🤔 I'm not doing any claims transforms, etc... just the simple/default setup

Back to this

> The reason for the 'complexity' is that the Azure AD provider does not provide email in the expected claim and we need to do some transformations. It turned out the Name claim was also the e-mail address, so I had to intercept the Notifications to pass in the Name claim as the Email claim

I don't have this problem at all so that seems odd you have to add additional logic

**Comment by clarkd** [comment] 2018-11-29 23:36
Might be worth leaving that running for a few days without logging in and
then try. See my comment RE inactivity above.

**Comment by CasperTDK** [comment] 2018-11-30 07:37
```
    <add key="umbracoTimeOutInMinutes" value="20" />
    <keepUserLoggedIn>false</keepUserLoggedIn>
    <add key="umbracoConfigurationStatus" value="7.7.13" />
```

Yeah the biggest issue is the sporadic nature. Earlier this week, the AD login worked for the authors until around 10AM, then it just stopped working until a restart of the appPool.

I guess we will make a custom build of umbraco and put logging everywhere in BackOfficeController. Do you have any other services/controllers you think it would be good to place more logging in?
We will need to make this build and push it to the customers and wait for days of testing, so i'd like to just add the logging once.

When you are testing, what umbraco version are you using and can you share the code snippet (just to make sure there are zero misunderstandings)? I could try and make the customer test it with their AD.
@Shazwazza

**Comment by CasperTDK** [comment] 2018-12-07 11:04
@Shazwazza  I've added logging and can confirm that

**Comment by CasperTDK** [comment] 2018-12-10 13:34
@Shazwazza  I am able to send you network log or anything else you need as well

**Comment by Shazwazza** [comment] 2018-12-11 02:19
I've had the AD provider on my site for a bit now without any issues and have left it for quite a while and still seems ok, the configuration I'm using is bare minimum, i've blogged about it https://shazwazza.com/post/configuring-azure-active-directory-login-with-umbraco/

AD should return the required claims without additional config but there might be an option you need to select as mentioned by Darren http://disq.us/p/1xjvv1i though this wasn't required for my setup

My site is running ` 7.12.4`

When logging in with an External provider, the request will come in at `BackOfficeController.Default` -> `RenderDefaultOrProcessExternalLoginAsync` -> `ExternalSignInAsync`

Do you have any custom HttpModules running at all? or other OWIN based code that could intercept these calls?

**Comment by CasperTDK** [comment] 2018-12-17 10:38
The reason why I am using AuthorizationCode instead of [autoLinkOptions.OnAutoLinking](https://our.umbraco.com/documentation/Reference/Security/auto-linking) is because of the e-mail bug i mentioned:
![image](https://user-images.githubusercontent.com/119062/50082057-53219780-01f0-11e9-8cb8-350627c746ee.png)

**Comment by CasperTDK** [comment] 2018-12-19 15:04
@Shazwazza  Yes, it does say unlink when I am able to login:
![image](https://user-images.githubusercontent.com/119062/50228175-a0943500-03a7-11e9-8986-67ae37163193.png)

Yeah I can definitely try and do this. The biggest issue here is that the error is sporadic and there be several days without hiccups. It *seems* that when multiple editors are using the AD login, the issue will occur faster, but I have no actual evidence here.
So if you have any other suggestions, that would be great

**Comment by gjelhus** [comment] 2019-01-03 14:23
Hi

We are experiencing the same issue with version 7.12.3 of umbraco, using ADFS on windows server 2016 as our authentication provider. It works for a few hours at best a day then it fails.  Restarting the application pool fixes the issue. 
We have so far been unable to reproduce the issue in our Test and QA environment, it only happens in production.
We have a pretty quick release cycle so if there is any logging you need done we should be able to do that, but any hints on where to look would be appreciated. We could even build a custom version of the sourcecode.

**Comment by CasperTDK** [comment] 2019-02-06 12:02
Hi guys. I have solved the issue with the following *hacks*:

  ```csharp
 public override void Configuration(IAppBuilder app)
        {
            app.UseKentorOwinCookieSaver();
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                CookieManager = new SystemWebCookieManager()
            });
...
```

Sources:
https://github.com/Sustainsys/owin-cookie-saver
https://dotnetcodetips.com/Tip/91/Azure-OWIN-website-login-gets-stuck-on-a-never-ending-redirect-loop

I call them a hack, but I do not completely understand the problem nor the fix... But we've had 100% stability for over a week now! Before it was a daily issue

**Comment by Shazwazza** [comment] 2019-02-06 12:07
Interesting and great! Hopefully this works for others too (please let me know)

I suppose this is why it is so hard to replicate. We have some cookie manager code built in to umbraco so it might be possible to leverage some of the work arounds listed in those various articles and in https://github.com/aspnet/AspNetKatana/wiki/System.Web-response-cookie-integration-issues

**Comment by gjelhus** [comment] 2019-02-25 14:28
Hi
Where in the pipeline did you include the third party cookie component  @CasperTDK  ? I gave it a try but no luck for me, but i have a feeling that order matters here. Any help would be greatly apricated :)

best regards
Tor Arne Gjelhus

**Comment by CasperTDK** [comment] 2019-02-25 16:44
Sure!

web.config appsettings 
```xml 
<appsettings>
  <add key="owin:appStartup" value="XXX.XXXOwinStartup" />
```

  ```csharp
 public class XXXOwinStartup : UmbracoDefaultOwinStartup
    {
        public override void Configuration(IAppBuilder app)
        {
            //https://dotnetcodetips.com/Tip/91/Azure-OWIN-website-login-gets-stuck-on-a-never-ending-redirect-loop
            app.UseKentorOwinCookieSaver();
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                CookieManager = new SystemWebCookieManager()
            });

           base.Configuration(app); //standard umbraco configuration
...
```

**Comment by gjelhus** [comment] 2019-03-04 09:43
@CasperTDK  Thank you very much. I will give it a go :)

**Comment by gjelhus** [comment] 2019-03-18 14:55
@CasperTDK  We have now over a week of stable auth  so i think its safe to say that this works, so than you very much  :) .
For others that might find this thread, the order you do things in matters. The custom cookiesaver must be setup BEFORE you do the regular  owin setup stuff as shown above. In my first try i did it after and then it did not work.

**Comment by Shazwazza** [comment] 2019-03-28 03:40
What we'll want to do is update the code in the project, the docs and the nuget package for https://www.nuget.org/packages/UmbracoCms.IdentityExtensions.AzureActiveDirectory/ to perhaps have this built in. 

What i'm unsure about at this point is if both of these things are required? `app.UseKentorOwinCookieSaver();` AND `SystemWebCookieManager` ?

**Comment by Lepike** [comment] 2019-04-04 08:32
@CasperTDK Thank you for this! Our solution have been up and running for a week without any failed logins.

**Comment by Insinfi** [comment] 2019-05-31 15:26
@CasperTDK When trying your solution I have encounter a problem I keep getting 417 response after been logged. That result into white page on umbraco.
I think it may come from the http-only on the UMB-XSRF-TOKEN cookie.
